/**
 * Service Tasmania-branded one-time-passcode email, matching the myServiceTas
 * verification email design (green banner, "Your code is", Service Tasmania footer).
 *
 * Email clients strip <style> and external fonts unreliably, so everything here is
 * table-based with inline styles and web-safe font fallbacks (Nunito is requested
 * but degrades gracefully to a sans-serif stack).
 */

// Hero green used across the myServiceTas web app banner.
const BRAND_GREEN = "#098851";
const TEXT_COLOR = "#292929";
const MUTED_COLOR = "#6b7280";
const FONT_STACK =
    "'Nunito', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";

// Tasmanian Government crest, served from the deployed Static Web App so it
// renders in clients that block inline/data-URI images (notably Gmail web and
// Outlook desktop). PNG (not SVG) because most email clients don't render SVG.
// Source asset: react-nextjs-sample/public/logos/tasmania-govt-black.png (108x100).
const TAS_GOVT_LOGO =
    "https://lively-plant-074801300.7.azurestaticapps.net/logos/tasmania-govt-black.png";

export interface OtpEmailContent {
    subject: string;
    html: string;
    plainText: string;
}

export interface BuildOtpEmailOptions {
    /** Recipient email address, shown in the greeting line. */
    email: string;
    /** The one-time passcode generated by Entra. */
    code: string;
    /** Sender display name, e.g. "myServiceTas". */
    brandName?: string;
}

export function buildOtpEmail({ email, code, brandName = "myServiceTas" }: BuildOtpEmailOptions): OtpEmailContent {
    const subject = "myServiceTas account email verification code";

    const plainText =
        `Verify your email address\n\n` +
        `Thanks for verifying your ${email} account!\n\n` +
        `Your code is: ${code}\n\n` +
        `Sincerely,\n${brandName}\n\n` +
        `This message was sent from an unmonitored email address. Please do not reply to this message.\n` +
        `Service Tasmania | Tasmanian Government`;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${subject}</title>
</head>
<body style="margin:0; padding:0; background-color:#f5f5f5;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;">
    <tr>
      <td align="center" style="padding:24px 12px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0"
               style="width:600px; max-width:600px; background-color:#ffffff; font-family:${FONT_STACK}; color:${TEXT_COLOR};">
          <!-- Green banner -->
          <tr>
            <td style="background-color:${BRAND_GREEN}; padding:22px 32px;">
              <span style="color:#ffffff; font-size:22px; font-weight:600;">Verify your email address</span>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px;">
              <p style="margin:0 0 24px 0; font-size:16px; line-height:1.5;">
                Thanks for verifying your <span style="color:#0066cc; text-decoration:underline;">${email}</span> account!
              </p>
              <p style="margin:0 0 24px 0; font-size:16px; line-height:1.5;">
                <strong>Your code is: ${code}</strong>
              </p>
              <p style="margin:0; font-size:16px; line-height:1.5;">Sincerely,</p>
              <p style="margin:0; font-size:16px; font-style:italic;">${brandName}</p>
            </td>
          </tr>
          <!-- Divider -->
          <tr>
            <td style="padding:0 32px;">
              <hr style="border:none; border-top:1px solid #e5e7eb; margin:0;" />
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:20px 32px 32px 32px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="font-size:12px; color:${MUTED_COLOR}; line-height:1.5; vertical-align:bottom;">
                    This message was sent from an unmonitored email address.<br />
                    Please do not reply to this message.
                  </td>
                  <td align="right" style="vertical-align:middle;">
                    <table role="presentation" cellpadding="0" cellspacing="0" align="right" style="border-collapse:collapse;">
                      <tr>
                        <td style="font-size:24px; font-weight:700; color:${TEXT_COLOR}; padding-right:14px; vertical-align:middle; white-space:nowrap;">Service&nbsp;Tasmania</td>
                        <td style="border-left:1px solid ${TEXT_COLOR}; padding-left:14px; vertical-align:middle;">
                          <img src="${TAS_GOVT_LOGO}" width="48" height="44" alt="Tasmanian Government" style="display:block; border:0; outline:none; text-decoration:none;" />
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

    return { subject, html, plainText };
}
