export const styles = {
    container: {
        maxWidth: "400px",
        margin: "40px auto",
        padding: "20px",
        border: "1px solid #ccc",
        borderRadius: "8px",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "15px",
    },
    input: {
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
        fontSize: "16px",
    },
    button: {
        padding: "10px",
        backgroundColor: "#0078d4",
        color: "white",
        border: "none",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "16px",
    },
    buttonDisabled: {
        padding: "10px",
        backgroundColor: "#6b7280",
        color: "white",
        border: "none",
        borderRadius: "4px",
        cursor: "not-allowed",
        fontSize: "16px",
    },
    error: {
        color: "#d13438",
        marginTop: "10px",
    },
    h2: {
        margin: "0 0 10px 0",
        textAlign: "center",
    },
    signed_in_msg: {
        padding: "20px",
        border: "1px solid #ddd",
        borderRadius: "4px",
        marginTop: "20px",
    },
    separator: {
        display: "flex",
        alignItems: "center",
        textAlign: "center",
        margin: "20px 0",
    },
    separatorLine: {
        flex: 1,
        borderBottom: "1px solid #ccc",
    },
    separatorText: {
        padding: "0 10px",
        color: "#666",
        fontSize: "14px",
        fontWeight: "500",
    },
    socialButton: {
        padding: "10px",
        backgroundColor: "#fff",
        color: "#333",
        border: "1px solid #ccc",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "16px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        transition: "background-color 0.2s, border-color 0.2s",
    },
    providerLogo: {
        fontSize: "20px",
        display: "flex",
        alignItems: "center",
    },
} as const;
